---

- name: Install
  tags:
  - install
  block:
  - name: install required packages
    package:
      name: "{{ item }}"
      state: present
    loop:
    - unzip

  - name: Install vault
    import_tasks: install.yml

- name: Configure
  tags:
  - config
  block:
  - name: Configure vault
    import_tasks: configure.yml

  - name: Create systemd Unit File
    template:
      src: vault.systemd.j2
      dest: /usr/lib/systemd/system/vault.service
    notify:
    - systemctl daemon-reload

  - name: Start vault
    systemd:
      name: vault
      state: started
    when: vault_manage_service

- name: Vault API setup
  tags:
  - api
  block:
  - set_fact:
      vault_url: "{% if vault_config.api_addr is defined %}{{ vault_config.api_addr }}{% else %}https://{{ vault_host }}:8200{% endif %}"

  - import_tasks: api/init.yml
    when: vault_auto_init

  - import_tasks: api/policies.yml
    tags: policies

