---

- name: Check if Vault is unsealed
  uri:
    url: "{{ vault_url }}/v1/sys/seal-status"
    method: GET
    headers:
      Content-Type: application/json
  run_once: true
  register: vault_status

- fail:
    msg: Vault in sealed
  when: vault_status.json.sealed

- set_fact:
    vault_request_token: "{% if root_token is defined %}{{ root_token }}{% else %}{{ vault_token }}{% endif %}"

- name: Create vault policies
  uri:
    url: "{{ vault_url }}/v1/sys/policy/{{ item.name }}"
    method: PUT
    status_code: 204
    headers:
      X-Vault-Token: "{{ vault_request_token }}"
      Content-Type: application/json
    body_format: json
    body:
      policy: "{{ item.policies | to_json }}"
  run_once: true
  loop: "{{ vault_policies }}"

