---

- name: Create Vault policies
  uri:
    url: "{{ vault_url }}/v1/sys/policy/{{ item.name }}"
    method: PUT
    status_code: 204
    headers:
      X-Vault-Token: "{{ vault_request_token }}"
      Content-Type: application/json
    body_format: json
    body:
      policy: "{{ item.policies | to_json }}"
  run_once: true
  loop: "{{ vault_policies }}"

