---

- name: Read secret engines
  uri:
    url: "{{ vault_url }}/v1/sys/mounts"
    method: GET
    status_code: 200
    headers:
      X-Vault-Token: "{{ vault_request_token }}"
      Content-Type: application/json
  register: r_secrets

- name: Enable Vault secret engines
  uri:
    url: "{{ vault_url }}/v1/sys/mounts/{{ item.path }}"
    method: POST
    status_code: 204
    headers:
      X-Vault-Token: "{{ vault_request_token }}"
      Content-Type: application/json
    body_format: json
    body: "{{ item.parameters | to_json }}"
  run_once: true
  loop: "{{ vault_secrets }}"
  when: item.path + '/' not in r_secrets.json.data

